export const countries = [
  { label: "Colombia", value: "Colombia" },
  { label: "Estados Unidos", value: "Estados Unidos" },
  { label: "España", value: "España" },
  { label: "México", value: "México" },
  { label: "Argentina", value: "Argentina" },
  { label: "Brasil", value: "Brasil" },
  { label: "Chile", value: "Chile" },
  { label: "Perú", value: "Perú" },
  { label: "Francia", value: "Francia" },
  { label: "Reino Unido", value: "Reino Unido" },
  { label: "Alemania", value: "Alemania" },
  { label: "Italia", value: "Italia" },
  { label: "Japón", value: "Japón" },
  { label: "China", value: "China" },
  { label: "Canadá", value: "Canadá" },
];

export const popularAirports = [
  { codigoIATA: "BOG", codigoICAO: "SKBO", nombre: "Aeropuerto El Dorado", ciudad: "Bogotá", pais: "Colombia" },
  { codigoIATA: "MDE", codigoICAO: "SKRG", nombre: "Aeropuerto José María Córdova", ciudad: "Medellín", pais: "Colombia" },
  { codigoIATA: "CLO", codigoICAO: "SKCL", nombre: "Aeropuerto Alfonso Bonilla Aragón", ciudad: "Cali", pais: "Colombia" },
  { codigoIATA: "CTG", codigoICAO: "SKCG", nombre: "Aeropuerto Rafael Núñez", ciudad: "Cartagena", pais: "Colombia" },
  { codigoIATA: "BAQ", codigoICAO: "SKBQ", nombre: "Aeropuerto Ernesto Cortissoz", ciudad: "Barranquilla", pais: "Colombia" },
  { codigoIATA: "SMR", codigoICAO: "SKSM", nombre: "Aeropuerto Simón Bolívar", ciudad: "Santa Marta", pais: "Colombia" },
  { codigoIATA: "ADZ", codigoICAO: "SKSP", nombre: "Aeropuerto Gustavo Rojas Pinilla", ciudad: "San Andrés", pais: "Colombia" },
  { codigoIATA: "PEI", codigoICAO: "SKPE", nombre: "Aeropuerto Matecaña", ciudad: "Pereira", pais: "Colombia" },
  { codigoIATA: "BGA", codigoICAO: "SKBG", nombre: "Aeropuerto Palonegro", ciudad: "Bucaramanga", pais: "Colombia" },
  { codigoIATA: "MIA", codigoICAO: "KMIA", nombre: "Miami International Airport", ciudad: "Miami", pais: "Estados Unidos" },
  { codigoIATA: "JFK", codigoICAO: "KJFK", nombre: "John F. Kennedy International Airport", ciudad: "New York", pais: "Estados Unidos" },
  { codigoIATA: "MAD", codigoICAO: "LEMD", nombre: "Adolfo Suárez Madrid-Barajas", ciudad: "Madrid", pais: "España" },
  { codigoIATA: "BCN", codigoICAO: "LEBL", nombre: "Josep Tarradellas Barcelona-El Prat", ciudad: "Barcelona", pais: "España" },
  { codigoIATA: "MEX", codigoICAO: "MMMX", nombre: "Aeropuerto Internacional Benito Juárez", ciudad: "Ciudad de México", pais: "México" },
  { codigoIATA: "CUN", codigoICAO: "MMUN", nombre: "Aeropuerto Internacional de Cancún", ciudad: "Cancún", pais: "México" },
  { codigoIATA: "EZE", codigoICAO: "SAEZ", nombre: "Aeropuerto Internacional Ministro Pistarini", ciudad: "Buenos Aires", pais: "Argentina" },
  { codigoIATA: "GRU", codigoICAO: "SBGR", nombre: "Aeropuerto Internacional de São Paulo-Guarulhos", ciudad: "São Paulo", pais: "Brasil" },
  { codigoIATA: "SCL", codigoICAO: "SCEL", nombre: "Aeropuerto Internacional Arturo Merino Benítez", ciudad: "Santiago", pais: "Chile" },
  { codigoIATA: "LIM", codigoICAO: "SPJC", nombre: "Aeropuerto Internacional Jorge Chávez", ciudad: "Lima", pais: "Perú" },
  { codigoIATA: "CDG", codigoICAO: "LFPG", nombre: "Charles de Gaulle Airport", ciudad: "Paris", pais: "Francia" },
  { codigoIATA: "LHR", codigoICAO: "EGLL", nombre: "Heathrow Airport", ciudad: "London", pais: "Reino Unido" },
];
